{% set version = '3.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-callr
  version: {{ version|replace("-", "_") }}

source:
  fn: callr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/callr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/callr/callr_{{ version }}.tar.gz
  sha256: ad935f61accbf7ac628c4705ebe1cc5e702d244895fc8ed6dfb2db669ba93aeb

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-r6
    - r-processx >=3.2.1
  run:
    - r-base
    - r-r6
    - r-processx >=3.2.1

test:
  commands:
    - $R -e "library('callr')"           # [not win]
    - "\"%R%\" -e \"library('callr')\""  # [win]

about:
  home: https://github.com/r-lib/callr#readme
  license: MIT
  summary: It is sometimes useful to perform a computation in a separate R process, without affecting
    the current R process at all. This packages does exactly that.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
