{% set version = "2.0.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-callr
  version: {{ version|replace("-", "_") }}

source:
  fn: callr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/callr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/callr/callr_{{ version }}.tar.gz
  sha256: f1f7d511b215eb88d8680edef09d31eb93b3ef8beb124f8edf0c82601f7575cc

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-r6
    - r-assertthat
    - r-crayon
    - r-debugme
    - r-testthat
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-r6
    - r-assertthat
    - r-crayon
    - r-debugme
    - r-testthat
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('callr')"  # [not win]
    - "\"%R%\" -e \"library('callr')\""  # [win]

about:
  home: https://cran.r-project.org/package=callr
  dev_url: https://github.com/r-lib/callr
  license: MIT
  summary: It is sometimes useful to perform a computation in a separate R process, without affecting
    the current R process at all. This packages does exactly that.
  license_family: MIT

extra:
  recipe-maintainers:
    - jdblischak
    - johanneskoester
    - bgruening
    - daler
